/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ProposalRouteImport } from './routes/proposal'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as StructureRouteImport } from './routes/structure'
import { Route as WorkingGroupRouteImport } from './routes/working-group'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalRoute = ProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const StructureRoute = StructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkingGroupRoute = WorkingGroupRouteImport.update({
  id: '/working-group',
  path: '/working-group',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/history': typeof HistoryRoute
  '/proposal': typeof ProposalRoute
  '/standards': typeof StandardsRoute
  '/structure': typeof StructureRoute
  '/working-group': typeof WorkingGroupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/history': typeof HistoryRoute
  '/proposal': typeof ProposalRoute
  '/standards': typeof StandardsRoute
  '/structure': typeof StructureRoute
  '/working-group': typeof WorkingGroupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/history': typeof HistoryRoute
  '/proposal': typeof ProposalRoute
  '/standards': typeof StandardsRoute
  '/structure': typeof StructureRoute
  '/working-group': typeof WorkingGroupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/documents'
    | '/history'
    | '/proposal'
    | '/standards'
    | '/structure'
    | '/working-group'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/documents'
    | '/history'
    | '/proposal'
    | '/standards'
    | '/structure'
    | '/working-group'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/documents'
    | '/history'
    | '/proposal'
    | '/standards'
    | '/structure'
    | '/working-group'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DocumentsRoute: typeof DocumentsRoute
  HistoryRoute: typeof HistoryRoute
  ProposalRoute: typeof ProposalRoute
  StandardsRoute: typeof StandardsRoute
  StructureRoute: typeof StructureRoute
  WorkingGroupRoute: typeof WorkingGroupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal': {
      id: '/proposal'
      path: '/proposal'
      fullPath: '/proposal'
      preLoaderRoute: typeof ProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structure': {
      id: '/structure'
      path: '/structure'
      fullPath: '/structure'
      preLoaderRoute: typeof StructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/working-group': {
      id: '/working-group'
      path: '/working-group'
      fullPath: '/working-group'
      preLoaderRoute: typeof WorkingGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DocumentsRoute: DocumentsRoute,
  HistoryRoute: HistoryRoute,
  ProposalRoute: ProposalRoute,
  StandardsRoute: StandardsRoute,
  StructureRoute: StructureRoute,
  WorkingGroupRoute: WorkingGroupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
